USE RBS;

SET foreign_key_checks = 0;

ALTER TABLE PEOPLE DISABLE KEYS; 

LOAD DATA LOCAL INFILE '/conectum/Areas/TI/crones/rbs/posadas_usr.txt'        REPLACE INTO TABLE PEOPLE FIELDS TERMINATED BY '|' ENCLOSED BY '"' LINES STARTING BY '#';

LOAD DATA LOCAL INFILE '/conectum/Areas/TI/crones/rbs/posadas_grados.txt'     REPLACE INTO TABLE GRADO FIELDS TERMINATED BY '|' ENCLOSED BY '"' LINES STARTING BY '#';

LOAD DATA LOCAL INFILE '/conectum/Areas/TI/crones/rbs/posadas_posiciones.txt' REPLACE INTO TABLE POSICION FIELDS TERMINATED BY '|' ENCLOSED BY '"' LINES STARTING BY '#';

LOAD DATA LOCAL INFILE '/conectum/Areas/TI/crones/rbs/posadas_nominas.txt'    REPLACE INTO TABLE NOMINA FIELDS TERMINATED BY '|' ENCLOSED BY '"' LINES STARTING BY '#';

LOAD DATA LOCAL INFILE '/conectum/Areas/TI/crones/rbs/mexicana_usr.txt'       REPLACE INTO TABLE PEOPLE FIELDS TERMINATED BY '|' ENCLOSED BY '"' LINES STARTING BY '#';

LOAD DATA LOCAL INFILE '/conectum/Areas/TI/crones/rbs/mexicana_grados.txt'     REPLACE INTO TABLE GRADO FIELDS TERMINATED BY '|' ENCLOSED BY '"' LINES STARTING BY '#';

LOAD DATA LOCAL INFILE '/conectum/Areas/TI/crones/rbs/mexicana_posiciones.txt'     REPLACE INTO TABLE POSICION FIELDS TERMINATED BY '|' ENCLOSED BY '"' LINES STARTING BY '#';

LOAD DATA LOCAL INFILE '/conectum/Areas/TI/crones/rbs/mexicana_nominas.txt'     REPLACE INTO TABLE NOMINA FIELDS TERMINATED BY '|' ENCLOSED BY '"' LINES STARTING BY '#';


UPDATE PEOPLE SET
FIRST_NAME = REPLACE ( FIRST_NAME,'~1', char(209) ),
LAST_NAME = REPLACE ( LAST_NAME,'~1', char(209) )
WHERE INSTR(FIRST_NAME, '~')>0
OR INSTR(LAST_NAME, '~')>0;

UPDATE PEOPLE SET
LAST_NAME = REPLACE (LAST_NAME, '-', ' ');


ALTER TABLE PEOPLE ENABLE KEYS; 

SET foreign_key_checks = 1;

