
--
-- Proveedores vs UO y UN
--
SELECT DISTINCT
       OU.NAME              UNIDAD_OPERATIVA
     , PVS.VENDOR_SITE_CODE UNIDAD_NEGOCIO
     , PV.VENDOR_NAME       PROVEEDOR
     , PV.SEGMENT1          RFC 
FROM PO_VENDORS PV,
     PO_VENDOR_SITES_ALL PVS,
     HR_ALL_ORGANIZATION_UNITS OU
WHERE PV.VENDOR_ID =PVS.VENDOR_ID
   AND PVS.ORG_ID = OU.ORGANIZATION_ID   
AND ROWNUM < 5000


--
-- Articulos
--
SELECT DISTINCT
    OU.NAME,
    MSI.segment1    CODIGO,
    MSI.DESCRIPTION NOMBRE_ARTICULO
FROM MTL_SYSTEM_ITEMS_B MSI,
     HR_ALL_ORGANIZATION_UNITS OU
WHERE MSI.ORGANIZATION_ID = OU.ORGANIZATION_ID
  AND MSI.ENABLED_FLAG = 'Y'
  AND MSI.ORGANIZATION_ID <> 517
  AND ROWNUM < 5000
     