SELECT ROW_ID,ROW_LOW_RANGE_OR_NAME,ROW_HIGH_RANGE,VALUE,EFFECTIVE_START_DATE,EFFECTIVE_END_DATE,BUSINESS_GROUP_ID,
LEGISLATION_CODE,USER_COLUMN_INSTANCE_ID,LEGISLATION_SUBGROUP,USER_ROW_ID,USER_COLUMN_ID,LAST_UPDATE_DATE,LAST_UPDATED_BY,
LAST_UPDATE_LOGIN,CREATED_BY,CREATION_DATE 
FROM PAY_USER_COLUMN_INSTANCES_V 
WHERE ( BUSINESS_GROUP_ID IS NULL OR BUSINESS_GROUP_ID = 81 )
AND ( LEGISLATION_CODE IS NULL OR LEGISLATION_CODE = 'MX' ) 
and (USER_COLUMN_ID=121) order by display_sequence, row_low_range_or_name