SET DEFINE OFF;

DROP TABLE REPORTS_LIST CASCADE CONSTRAINTS;

CREATE TABLE REPORTS_LIST
(
  REPORT_ID          VARCHAR2(30 BYTE),
  DESCRIPTION        VARCHAR2(100 BYTE),
  MODULE_NAME        VARCHAR2(30 BYTE)
)
NOLOGGING 
;

-- Insert Sample Data-- ------------------
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_1', 'Sample Report 1', 'Module_1');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_2', 'Sample Report 2', 'Module_2');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_3', 'Sample Report 3', 'Module_3');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_4', 'Sample Report 4', 'Module_4');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_5', 'Sample Report 5', 'Module_5');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_6', 'Sample Report 6', 'Module_6');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_7', 'Sample Report 7', 'Module_7');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_8', 'Sample Report 8', 'Module_8');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_9', 'Sample Report 9', 'Module_9');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_10', 'Sample Report 10', 'Module_10');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_11', 'Sample Report 11', 'Module_11');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_12', 'Sample Report 12', 'Module_12');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_13', 'Sample Report 13', 'Module_13');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_14', 'Sample Report 14', 'Module_14');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_15', 'Sample Report 15', 'Module_15');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_16', 'Sample Report 16', 'Module_16');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_17', 'Sample Report 17', 'Module_17');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_18', 'Sample Report 18', 'Module_18');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_19', 'Sample Report 19', 'Module_19');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_20', 'Sample Report 20', 'Module_20');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_21', 'Sample Report 21', 'Module_21');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_22', 'Sample Report 22', 'Module_22');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_23', 'Sample Report 23', 'Module_23');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_24', 'Sample Report 24', 'Module_23');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_25', 'Sample Report 25', 'Module_24');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_26', 'Sample Report 26', 'Module_25');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_27', 'Sample Report 27', 'Module_26');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_28', 'Sample Report 28', 'Module_27');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_29', 'Sample Report 29', 'Module_27');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_30', 'Sample Report 30', 'Module_28');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_31', 'Sample Report 31', 'Module_29');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_32', 'Sample Report 32', 'Module_29');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_33', 'Sample Report 33', 'Module_30');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_34', 'Sample Report 34', 'Module_31');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_35', 'Sample Report 35', 'Module_32');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_36', 'Sample Report 36', 'Module_33');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_37', 'Sample Report 37', 'Module_34');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_38', 'Sample Report 38', 'Module_35');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_39', 'Sample Report 39', 'Module_36');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_40', 'Sample Report 40', 'Module_37');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_41', 'Sample Report 41', 'Module_38');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_42', 'Sample Report 42', 'Module_38');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_43', 'Sample Report 43', 'Module_38');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_44', 'Sample Report 44', 'Module_39');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_45', 'Sample Report 45', 'Module_40');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_46', 'Sample Report 46', 'Module_41');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_47', 'Sample Report 47', 'Module_42');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_48', 'Sample Report 48', 'Module_43');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_49', 'Sample Report 49', 'Module_44');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_50', 'Sample Report 50', 'Module_45');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_51', 'Sample Report 51', 'Module_46');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_52', 'Sample Report 52', 'Module_47');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_53', 'Sample Report 53', 'Module_48');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_54', 'Sample Report 54', 'Module_49');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_55', 'Sample Report 55', 'Module_50');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_56', 'Sample Report 56', 'Module_51');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_57', 'Sample Report 57', 'Module_51');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_58', 'Sample Report 58', 'Module_52');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_59', 'Sample Report 59', 'Module_53');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_60', 'Sample Report 60', 'Module_54');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_61', 'Sample Report 61', 'Module_55');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_62', 'Sample Report 62', 'Module_56');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_63', 'Sample Report 63', 'Module_57');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_64', 'Sample Report 64', 'Module_58');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_65', 'Sample Report 65', 'Module_59');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_66', 'Sample Report 66', 'Module_60');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_67', 'Sample Report 67', 'Module_61');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_68', 'Sample Report 68', 'Module_62');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_69', 'Sample Report 69', 'Module_63');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_70', 'Sample Report 70', 'Module_63');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_71', 'Sample Report 71', 'Module_64');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_72', 'Sample Report 72', 'Module_65');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_73', 'Sample Report 73', 'Module_66');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_74', 'Sample Report 74', 'Module_67');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_75', 'Sample Report 75', 'Module_68');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_76', 'Sample Report 76', 'Module_69');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_77', 'Sample Report 77', 'Module_70');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_78', 'Sample Report 78', 'Module_71');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_79', 'Sample Report 79', 'Module_72');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_80', 'Sample Report 80', 'Module_73');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_81', 'Sample Report 81', 'Module_74');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_82', 'Sample Report 82', 'Module_75');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_83', 'Sample Report 83', 'Module_76');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_84', 'Sample Report 84', 'Module_77');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_85', 'Sample Report 85', 'Module_78');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_86', 'Sample Report 86', 'Module_79');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_87', 'Sample Report 87', 'Module_80');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_88', 'Sample Report 88', 'Module_81');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_89', 'Sample Report 89', 'Module_82');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_90', 'Sample Report 90', 'Module_83');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_91', 'Sample Report 91', 'Module_91');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_92', 'Sample Report 92', 'Module_91');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_93', 'Sample Report 93', 'Module_92');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_94', 'Sample Report 94', 'Module_93');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_95', 'Sample Report 95', 'Module_94');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_96', 'Sample Report 96', 'Module_95');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_97', 'Sample Report 97', 'Module_96');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_98', 'Sample Report 98', 'Module_97');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_99', 'Sample Report 99', 'Module_98');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_100', 'Sample Report 100', 'Module_99');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_101', 'Sample Report 101', 'Module_100');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_102', 'Sample Report 102', 'Module_101');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_103', 'Sample Report 103', 'Module_102');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_104', 'Sample Report 104', 'Module_103');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_105', 'Sample Report 105', 'Module_104');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_106', 'Sample Report 106', 'Module_105');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_107', 'Sample Report 107', 'Module_106');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_108', 'Sample Report 108', 'Module_107');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_109', 'Sample Report 109', 'Module_108');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_110', 'Sample Report 110', 'Module_109');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_111', 'Sample Report 111', 'Module_110');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_112', 'Sample Report 112', 'Module_111');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_113', 'Sample Report 113', 'Module_112');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_114', 'Sample Report 114', 'Module_113');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_115', 'Sample Report 115', 'Module_115');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_116', 'Sample Report 116', 'Module_116');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_117', 'Sample Report 117', 'Module_116');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_118', 'Sample Report 118', 'Module_117');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_119', 'Sample Report 119', 'Module_118');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_120', 'Sample Report 120', 'Module_119');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_121', 'Sample Report 121', 'Module_120');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_122', 'Sample Report 122', 'Module_121');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_123', 'Sample Report 123', 'Module_122');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_124', 'Sample Report 124', 'Module_123');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_125', 'Sample Report 125', 'Module_124');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_126', 'Sample Report 126', 'Module_125');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_127', 'Sample Report 127', 'Module_126');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_128', 'Sample Report 128', 'Module_127');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_129', 'Sample Report 129', 'Module_128');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_130', 'Sample Report 130', 'Module_129');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_131', 'Sample Report 131', 'Module_130');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_132', 'Sample Report 132', 'Module_131');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_133', 'Sample Report 133', 'Module_132');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_134', 'Sample Report 134', 'Module_133');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_135', 'Sample Report 135', 'Module_134');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_136', 'Sample Report 136', 'Module_135');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_137', 'Sample Report 137', 'Module_136');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_138', 'Sample Report 138', 'Module_137');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_139', 'Sample Report 139', 'Module_138');
Insert into REPORTS_LIST   (REPORT_ID, DESCRIPTION, MODULE_NAME) Values   ('REPORT_140', 'Sample Report 140', 'Module_139');
COMMIT;
