

SELECT X.*
FROM WF_NOTIFICATIONS x
WHERE 1=1
--AND RECIPIENT_ROLE LIKE 'CONE-GVARGAS'
--AND UPPER(SUBJECT) LIKE UPPER('%OIE80086%')
AND USER_KEY ='OIE80086'
and item_key = '80086'
AND BEGIN_DATE > TO_DATE('17-05-2009', 'DD-MM-YYYY')
ORDER BY BEGIN_DATE DESC
