
  SELECT DISTINCT 
                  FRG.REQUEST_GROUP_NAME 
                  --,FRT.RESPONSIBILITY_NAME 
                  --,FRGU.REQUEST_UNIT_TYPE, 
                  --FRGU.REQUEST_UNIT_ID, 
                  ,'     '||FCPT.USER_CONCURRENT_PROGRAM_NAME
    FROM APPS.FND_RESPONSIBILITY FR, 
         APPS.FND_RESPONSIBILITY_TL FRT, 
         APPS.FND_REQUEST_GROUPS FRG, 
         APPS.FND_REQUEST_GROUP_UNITS FRGU, 
         APPS.FND_CONCURRENT_PROGRAMS_TL FCPT
   WHERE FRT.RESPONSIBILITY_ID = FR.RESPONSIBILITY_ID AND 
         FRG.REQUEST_GROUP_ID = FR.REQUEST_GROUP_ID AND 
         FRGU.REQUEST_GROUP_ID = FRG.REQUEST_GROUP_ID AND 
         FCPT.CONCURRENT_PROGRAM_ID = FRGU.REQUEST_UNIT_ID 
        and UPPER (FCPT.USER_CONCURRENT_PROGRAM_NAME) like  UPPER ('CMR%')
ORDER BY 1;



