UPDATE FND_CONCURRENT_PROGRAMS B SET 
B.ENABLE_TRACE ='Y'
WHERE  B.ENABLED_FLAG = 'Y' 
AND (B.APPLICATION_ID, B.CONCURRENT_PROGRAM_ID) IN
      (
        SELECT T.APPLICATION_ID, T.CONCURRENT_PROGRAM_ID
        FROM FND_CONCURRENT_PROGRAMS_TL T  
        WHERE T.LANGUAGE = 'ESA' 
        AND T.USER_CONCURRENT_PROGRAM_NAME LIKE 'CSA%'        
       );
       

