


--- 
-- Desbloquea responsabilidades de la nueva version.
--


INSERT INTO wf_local_user_roles
SELECT 'CONE-WAVILA', ROLE_NAME,  USER_ORIG_SYSTEM, USER_ORIG_SYSTEM_ID, ROLE_ORIG_SYSTEM, ROLE_ORIG_SYSTEM_ID, START_DATE, EXPIRATION_DATE
, SECURITY_GROUP_ID, PARTITION_ID, OWNER_TAG, CREATED_BY, SYSDATE, LAST_UPDATED_BY, SYSDATE, LAST_UPDATE_LOGIN, ASSIGNMENT_TYPE, PARENT_ORIG_SYSTEM
, PARENT_ORIG_SYSTEM_ID, USER_START_DATE, ROLE_START_DATE, USER_END_DATE, ROLE_END_DATE, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE
, ASSIGNMENT_REASON
--role_name, role_orig_system_id, expiration_date  
FROM wf_local_user_roles     
WHERE USER_NAME LIKE 'CONE-GVARGAS'
AND ROLE_ORIG_SYSTEM_ID = 50147
;


UPDATE APPLSYS.WF_LOCAL_USER_ROLES SET
expiration_date = NULL
,effective_end_date = TO_DATE ('01-01-2015', 'dd-mm-yyyy')
WHERE USER_NAME LIKE 'CONE-GVARGAS'
--AND role_orig_system_id IN ( 50147)
AND ROLE_NAME LIKE 'FND_RESP|XBOL|APPLICATIONS_ADMINISTRATION|STANDARD' 
;

UPDATE APPLSYS.WF_USER_ROLE_ASSIGNMENTS SET
END_DATE = NULL
,EFFECTIVE_END_DATE = TO_DATE('01-01-9999', 'DD-MM-YYYY')
WHERE USER_NAME LIKE 'CONE-GVARGAS'
AND ROLE_NAME LIKE 'FND_RESP|XBOL|APPLICATIONS_ADMINISTRATION|STANDARD'
;

SELECT *
FROM APPLSYS.wf_local_user_roles
WHERE USER_NAME LIKE 'CONE-GVARGAS'
AND ROLE_NAME not LIKE '%'
;