UPDATE FND_DESCR_FLEX_COLUMN_USAGES
SET DEFAULT_VALUE = REPLACE ( DEFAULT_VALUE,'PGPDAI', 'TGPDAI')
/ 

UPDATE FND_DESCR_FLEX_COLUMN_USAGES
SET DEFAULT_VALUE = REPLACE ( DEFAULT_VALUE,'pgpdai', 'tgpdai')
/
 
COMMIT
/
