
  SELECT FLEX_VALUE,
         DESCRIPTION,
         SUMMARY_FLAG,
         FLEX_VALUE_SET_ID,
         PARENT_FLEX_VALUE
    FROM FND_FLEX_VALUE_CHILDREN_V
   WHERE  (PARENT_FLEX_VALUE = 'CP0033')
ORDER BY flex_value